#!/usr/bin/env sh

cd $(dirname "$0")/..
WORKING_DIR=$(pwd)

IMAGE_NAME=gk-rdfizer
TIMESTAMP=$(date +%s)

source_type=sh # TODO get as arg

docker run --rm \
  -v "${WORKING_DIR}/_tmp":/data \
  ${IMAGE_NAME} \
    --input "./datasets/${source_type}" \
    --input-format ${source_type} \
    --output-dir "./output/${source_type}-${TIMESTAMP}" \
    --output-format turtle